### ISSUE TITLE
KeyError: 'Tie'

### ISSUE THREAD

**Issue by 2press** [2press/sc2monitor#3]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sc2monitor/controller.py", line 717, in run
    raise result
  File "/usr/local/lib/python3.7/site-packages/sc2monitor/controller.py", line 213, in query_player
    await self.process_player(complete_data, new)
  File "/usr/local/lib/python3.7/site-packages/sc2monitor/controller.py", line 280, in process_player
    = await self.check_match_history(complete_data)
  File "/usr/local/lib/python3.7/site-packages/sc2monitor/controller.py", line 241, in check_match_history
    needed = data['missing'][match['result'].describe()] > 0
KeyError: 'Tie'
```

**Comment by 2press** [comment]
Fixed in https://github.com/2press/sc2monitor/commit/8b7b5c15f9babbbc9ba9a27a50ce2a61404a6b8a.
